services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: speed-roulette
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  
  backend:
    build: /backend
    container_name: backend
    ports:
      - '8080:8080'
    depends_on:
      - db
      - redis

  frontend:
    build: /frontend
    container_name: frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend

volumes:
  postgres_data: